name: "Combine Files"
description: "Combine image data files into one"
inputs:
  array:
    description: "Array of folder names within bin/extras"
    required: true
  build_dir:
    description: "Directory to sync extra files into"
    required: true
outputs:
  directory:
    description: "Directory where the new files are stored"
    value: ${{ steps.permutations.outputs.directory }}

runs:
  using: "composite"

  steps:
    - name: Rsync Files
      shell: bash
      env:
        array: "${{ inputs.array }}"
        out_dir: "${{ inputs.build_dir }}"
      run: |
        echo "$array" | jq ".[]" | while read -r extra; do
          rsync -W --no-compress bin/extras/$extra/files $out_dir/files;
        done

        ls -R $out_dir

    - name: Combine Packages
      id: combine
      shell: python
      env:
        array: "${{ inputs.array }}"
        out_dir: "${{ inputs.build_dir }}"
      run: |
        import os
        import json

        # Read base files
        with open("bin/base/packages.json", "r") as f:
          packages = json.load(f)

        out_dir = os.environ["out_dir"]

        with open(os.environ["GITHUB_OUTPUT"], "a") as fh:
          print(f"directory={out_dir}", file=fh)

        # Iterate over extras dirs and combine with base files
        extras = json.loads(os.environ["array"])

        for extra in extras:
          base_path = os.path.join("bin/extras", extra)

          try:
            with open(os.path.join(base_path, "packages.json")) as f:
              packages += json.load(f)
          except FileNotFoundError:
            pass

        with open(os.path.join(out_dir, "packages.json"), "w") as f:
          json.dumps(packages)
