name: build
on:
  schedule:
    - cron: "0 0 * * 0" # Every Sunday
  workflow_dispatch:
  push:
    branches:
      - main

env:
  ofs_version: "v4.0.3"
  target_prefix: "bcm27xx/"
  openwrt_build_api: "https://sysupgrade.openwrt.org/api/v1/build"
  openwrt_image_store: "https://sysupgrade.openwrt.org/store"
  outdir: "./artifacts"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        openwrt-version:
          - 23.05.2
        package: # Extracted from https://openwrt.org/toh/raspberry_pi_foundation/raspberry_pi
          - { target: bcm2708, id: rpi }
          - { target: bcm2709, id: rpi-2 }
          - { target: bcm2710, id: rpi-3 }
          - { target: bcm2711, id: rpi-4 }

    steps:
      - uses: actions/checkout@v3

      - name: Setup
        run: |
          mkdir -p ${{ env.outdir }}
          echo "artifact_name=openwrt-${{matrix.openwrt-version}}-${{matrix.package.id}}.img.gz" >> $GITHUB_ENV
          echo "artifact_path=${{env.outdir}}/openwrt-${{matrix.openwrt-version}}-${{matrix.package.id}}.img.gz" >> $GITHUB_ENV

      - name: Read packages
        uses: juliangruber/read-file-action@v1
        id: package
        with:
          path: ./img/packages.json

      - name: Read defaults
        uses: juliangruber/read-file-action@v1
        id: defaults
        with:
          path: ./img/boot.sh

      - name: Request OpenWRT build
        uses: fjogeleit/http-request-action@v1
        id: request
        with:
          url: "${{ env.openwrt_build_api }}"
          method: "POST"
          customHeaders: '{"Content-Type": "application/json"}'
          data: '{
            "profile": "${{ matrix.package.id }}",
            "target": "${{ env.target_prefix }}${{ matrix.package.target }}",
            "packages": ${{steps.package.outputs.content}},
            "defaults": "${{ steps.defaults.outputs.content }}",
            "version": "${{ matrix.openwrt-version }}",
            "diff_packages": true,
            "client": "ofs/${{ env.ofs_version }}"
            }'

      - name: Create build url
        run: |
          echo ${{steps.request.outputs.response}}
          echo ${{steps.request.outputs.response.request_hash}}
          echo "build_hash=${{ fromJson(steps.request.outputs.response).request_hash}}" >> $GITHUB_ENV
          echo "build_url=${{ env.openwrt_build_api}}/${{fromJson(steps.request.outputs.response).request_hash}}" >> $GITHUB_ENV

      - name: Wait for OpenWRT build
        uses: mydea/action-wait-for-api@v1
        with:
          url: "${{ env.build_url}}"
          headers: '{"Content-Type": "application/json"}'
          expected-status: "200"
          timeout: "900"

      - name: Download factory image
        run: |
          image_name=$(curl -s -H 'Content-Type: application/json' '${{ env.build_url }}' \
            | jq -r '.images[] | select(.filesystem=="ext4" and .type=="factory" ) | .name');

          wget -q -O ${{ env.artifact_path }} \
          ${{env.openwrt_image_store}}/${{env.build_hash}}/${image_name};

      - uses: actions/upload-artifact@v3
        with:
          name: ${{ env.artifact_name }}
          path: ${{ env.artifact_path }}
