name: build
on:
  schedule:
    - cron: "0 0 * * 0" # Every Sunday
  workflow_dispatch:
  push:
    branches:
      - main

env:
  ofs_version: "v4.0.3"
  target_prefix: "bcm27xx/"
  openwrt_build_api: "https://sysupgrade.openwrt.org/api/v1/build"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        openwrt-version:
          - 23.05.2
        package: # Extracted from https://openwrt.org/toh/raspberry_pi_foundation/raspberry_pi
          - { target: bcm2708, id: rpi }
          - { target: bcm2709, id: rpi-2 }
          - { target: bcm2710, id: rpi-3 }
          - { target: bcm2711, id: rpi-4 }

    steps:
      - uses: actions/checkout@v3

      - name: Read packages
        uses: juliangruber/read-file-action@v1
        id: package
        with:
          path: ./img/packages.json

      - name: Read defaults
        uses: juliangruber/read-file-action@v1
        id: defaults
        with:
          path: ./img/defaults

      - name: Request OpenWRT build
        uses: fjogeleit/http-request-action@v1
        id: request
        with:
          url: "${{ env.openwrt_build_api }}"
          method: "POST"
          customHeaders: '{"Content-Type": "application/json"}'
          data: '{
            "profile": "${{ matrix.package.id }}",
            "target": "${{ env.target_prefix }}${{ matrix.package.target }}",
            "packages": ${{steps.package.outputs.content}},
            "defaults": "${{ steps.defaults.outputs.content }}",
            "version": "${{ matrix.openwrt-version }}",
            "diff_packages": true,
            "client": "ofs/${{ env.ofs_version }}"
            }'

      - name: Create build url
        run: |
          echo ${{steps.request.outputs.response}}
          echo ${{steps.request.outputs.response.request_hash}}
          echo "build_url=${{ env.openwrt_build_api}}/${{fromJson(steps.request.outputs.response).request_hash}}" >> $GITHUB_ENV

      - name: Wait for OpenWRT build
        uses: mydea/action-wait-for-api@v1
        with:
          url: "${{ env.build_url}}"
          headers: '{"Content-Type": "application/json"}'
          expected-status: "200"
          timeout: "300"

      - name: Get OpenWRT build data
        uses: fjogeleit/http-request-action@v1
        id: data
        with:
          url: "${{ env.build_url}}"
          method: "GET"
          customHeaders: '{"Content-Type": "application/json"}'

      - name: Select factory image
        uses: sergeysova/jq-action@v2
        id: image
        with:
          cmd: |
            curl -H 'Content-Type: application/json' '${{ env.build_url }}' \
            | jq '.images[] | select(.filesystem=="ext4" and .type=="factory" ) | .name'

      - name: Show Response
        run: |
          echo ${{ steps.image.outputs.value }}
