name: build
on:
  schedule:
    - cron: "0 0 * * 0" # Every Sunday
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      image_dirs: ${{ steps.images.outputs.dirs }}
      openwrt-config: ${{ steps.openwrt.outputs.config }}

    steps:
      - uses: actions/checkout@v3

      - name: Read OpenWRT config
        id: openwrt
        run: |
          # Read multiline json without needing to escape
          echo "config<<EOF" >> $GITHUB_OUTPUT
          cat ".github/configs/openwrt.json" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Get image types
        id: images
        run: echo "dirs=$(ls -d img/* | jq -R -s -c 'split("\n")[:-1]')" >> $GITHUB_OUTPUT

  build:
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        version: ${{ fromJson(needs.setup.outputs.openwrt-config).versions }}
        firmware: ${{ fromJson(needs.setup.outputs.openwrt-config).firmware }}
        image_dir: ${{ fromJson(needs.setup.outputs.image_dirs)}}

    steps:
      - uses: actions/checkout@v3

      - name: setup
        id: setup
        env:
          image_dir: ${{ matrix.image_dir }}
        run: |
          echo "image_name=${image_dir##*/}" >> $GITHUB_OUTPUT #https://stackoverflow.com/a/73467112

      - uses: actions/cache@v3
        id: openwrt-cache
        with:
          path: "~/openwrt-artifacts"
          key: ${{ matrix.version }}-${{ matrix.firmware.id }}-${{ hashFiles(format('{0}/*', matrix.image_dir) )}}

      - uses: ./.github/actions/fetch-openwrt-image
        if: steps.openwrt-cache.cache-hit != 'true'
        id: openwrt
        with:
          version: ${{ matrix.version }}
          firmware_id: ${{ matrix.firmware.id}}
          firmware_target: ${{ matrix.firmware.target }}
          packages: ${{ matrix.image_dir }}/packages.json
          boot: ${{ matrix.image_dir }}/boot.sh
          outdir: "~/openwrt-artifacts"

      - uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.version }}-${{ matrix.firmware.id }}-${{ steps.setup.outputs.image_name }}.img.gz
          path: ${{ steps.openwrt.outputs.image }}
