name: build
on:
  schedule:
    - cron: "0 0 * * 0" # Every Sunday
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      extras: ${{ steps.permutations.outputs.permutations }}
      openwrt-config: ${{ steps.openwrt.outputs.config }}

    steps:
      - uses: actions/checkout@v3

      - name: Read OpenWRT config
        id: openwrt
        run: |
          # Read multiline json without needing to escape
          echo "config<<EOF" >> $GITHUB_OUTPUT
          cat ".github/configs/openwrt.json" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Get image extras
        id: extras
        run: echo "dirs=$(ls bin/extras | jq -R -s -c 'split("\n")[:-1]')" >> $GITHUB_OUTPUT

      - name: Extra permutations
        id: permutations
        uses: ./.github/actions/permutations
        with:
          array: "${{ steps.extras.outputs.dirs }}"

  build:
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        version: ${{ fromJson(needs.setup.outputs.openwrt-config).versions }}
        firmware: ${{ fromJson(needs.setup.outputs.openwrt-config).firmware }}
        extras: ${{ fromJson(needs.setup.outputs.extras)}}

    steps:
      - uses: actions/checkout@v3

      - name: setup
        id: setup
        env:
          extras: ${{ toJson(matrix.extras) }}
        run: |
          echo "image_name=$(echo $extras | jq -c -r 'join("-")')" >> $GITHUB_OUTPUT
          mkdir -p /home/runner/build/openwrt/ && \
          cp -r bin/base/* /home/runner/build/openwrt/

      - name: Create combined files
        id: combined
        uses: ./.github/actions/combine-file
        with:
          array: "${{ toJson(matrix.extras) }}"
          build_dir: /home/runner/build/openwrt/

      - uses: actions/cache@v3
        id: openwrt-cache
        with:
          path: ./openwrt-artifacts
          key: ${{ matrix.version }}-${{ matrix.firmware.id }}-${{ hashFiles("/home/runner/build/openwrt/")}}

      - uses: ./.github/actions/fetch-openwrt-image
        if: steps.openwrt-cache.outputs.cache-hit != 'true'
        id: openwrt
        with:
          version: ${{ matrix.version }}
          firmware_id: ${{ matrix.firmware.id}}
          firmware_target: ${{ matrix.firmware.target }}
          packages: ${{ steps.combined.outputs.packages_path }}
          files: ${{ steps.combined.outputs.files_path }}
          outdir: ./openwrt-artifacts

      - uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.version }}-${{ matrix.firmware.id }}-${{ steps.setup.outputs.image_name }}.img.gz
          path: "./openwrt-artifacts/*.img.gz"
